// src/components/FehlzeitDetailModal.tsx
import React from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from './ui/dialog';
import { Badge } from './ui/badge';
import { Button } from './ui/button';
import { Card } from './ui/card';
import { Separator } from './ui/separator';
import { CheckCircle, AlertCircle, Paperclip, Lock, Info, Edit2, Trash2, Calendar, Clock, User, FileText, Shield, HelpCircle } from 'lucide-react';

interface FehlzeitEntry {
  id: string;
  studentName: string;
  studentClass: string;
  courseClass: string;
  date: string;
  dateRange?: string;
  duration: 'Ganzer Tag' | 'Zeitfenster';
  status: 'krankgemeldet' | 'unentschuldigt' | 'beurlaubt' | 'ungeklärt' | 'verspätet';
  reason: string;
  hasAttachment: boolean;
  hasAccess: boolean;
  createdBy: string;
  createdAt: string;
  sourceType: 'eltern-app' | 'anwesenheit' | 'schuleingabe';
  lastEditedBy?: string;
  lastEditedAt?: string;
  endDate?: string; // For multi-day absences
  isMultiDay?: boolean; // To track if this is part of a multi-day absence
}

interface FehlzeitDetailModalProps {
  entry: FehlzeitEntry | null;
  isOpen: boolean;
  onClose: () => void;
  onEdit: (entry: FehlzeitEntry) => void;
  onDelete: (id: string) => void;
}

function StatusDisplay({ status, endDate, isMultiDay }: { 
  status: 'krankgemeldet' | 'unentschuldigt' | 'beurlaubt' | 'ungeklärt' | 'verspätet';
  endDate?: string;
  isMultiDay?: boolean;
}) {
  const getStatusText = (baseStatus: string) => {
    if (isMultiDay && endDate) {
      return `${baseStatus} bis ${endDate}`;
    }
    return baseStatus;
  };

  switch (status) {
    case 'krankgemeldet':
      return (
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-2 px-3 py-2 bg-green-100 text-green-800 rounded-lg">
            <CheckCircle className="h-4 w-4" />
            <span className="font-medium">{getStatusText('Krankgemeldet')}</span>
          </div>
        </div>
      );
    case 'beurlaubt':
      return (
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-2 px-3 py-2 bg-blue-100 text-blue-800 rounded-lg">
            <Shield className="h-4 w-4" />
            <span className="font-medium">{getStatusText('Beurlaubt')}</span>
          </div>
        </div>
      );
    case 'verspätet':
      return (
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-2 px-3 py-2 bg-yellow-100 text-yellow-800 rounded-lg">
            <Clock className="h-4 w-4" />
            <span className="font-medium">{getStatusText('Verspätet')}</span>
          </div>
        </div>
      );
    case 'ungeklärt':
      return (
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-2 px-3 py-2 bg-gray-100 text-gray-800 rounded-lg">
            <HelpCircle className="h-4 w-4" />
            <span className="font-medium">{getStatusText('Ungeklärt')}</span>
          </div>
        </div>
      );
    case 'unentschuldigt':
      return (
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-2 px-3 py-2 bg-red-100 text-red-800 rounded-lg">
            <AlertCircle className="h-4 w-4" />
            <span className="font-medium">{getStatusText('Unentschuldigt')}</span>
          </div>
        </div>
      );
    default:
      return (
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-2 px-3 py-2 bg-gray-100 text-gray-800 rounded-lg">
            <HelpCircle className="h-4 w-4" />
            <span className="font-medium">{getStatusText('Unbekannt')}</span>
          </div>
        </div>
      );
  }
}

function AttachmentDisplay({ hasAttachment, hasAccess }: { hasAttachment: boolean; hasAccess: boolean }) {
  if (!hasAttachment) {
    return (
      <div className="flex items-center gap-2 text-muted-foreground">
        <FileText className="h-4 w-4" />
        <span>Kein Nachweis vorhanden</span>
      </div>
    );
  }
  
  if (!hasAccess) {
    return (
      <div className="flex items-center gap-2 text-muted-foreground">
        <Lock className="h-4 w-4" />
        <span>Nachweis vorhanden (kein Zugriff)</span>
      </div>
    );
  }
  
  return (
    <div className="flex items-center gap-2 text-foreground">
      <Paperclip className="h-4 w-4" />
      <span>Nachweis vorhanden</span>
      <Button variant="outline" size="sm">
        Anzeigen
      </Button>
    </div>
  );
}

export function FehlzeitDetailModal({ entry, isOpen, onClose, onEdit, onDelete }: FehlzeitDetailModalProps) {
  if (!entry) return null;

  const handleDelete = () => {
    if (confirm('Fehlzeit wirklich löschen?')) {
      onDelete(entry.id);
      onClose();
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto p-4">
        <DialogHeader className="pb-2">
          <DialogTitle className="flex items-center gap-2">
            <User className="h-5 w-5" />
            Fehlzeit Details
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4">
          {/* Student Information */}
          <Card className="p-3">
            <div className="space-y-2">
              <h3 className="flex items-center gap-2">
                <User className="h-4 w-4" />
                Schüler*in
              </h3>
              <div>
                <div className="flex items-center gap-2">
                  <span className="font-medium">{entry.studentName}</span>
                  <Badge variant="outline">{entry.studentClass}</Badge>
                </div>
              </div>
            </div>
          </Card>

          {/* Source Type */}
          <Card className="p-3">
            <div className="space-y-2">
              <h3 className="flex items-center gap-2">
                <Info className="h-4 w-4" />
                Art der Meldung
              </h3>
              <div className="flex items-center gap-2">
                {entry.sourceType === 'eltern-app' && (
                  <Badge variant="outline" className="bg-blue-50 text-blue-700 border-blue-200">
                    <Info className="h-3 w-3 mr-1" />
                    Eltern-App
                  </Badge>
                )}
                {entry.sourceType === 'anwesenheit' && (
                  <Badge variant="outline" className="bg-orange-50 text-orange-700 border-orange-200">
                    <CheckCircle className="h-3 w-3 mr-1" />
                    Anwesenheit/Klassenbuch
                  </Badge>
                )}
                {entry.sourceType === 'schuleingabe' && (
                  <Badge variant="outline" className="bg-purple-50 text-purple-700 border-purple-200">
                    <Shield className="h-3 w-3 mr-1" />
                    Schuleingabe
                  </Badge>
                )}
              </div>
            </div>
          </Card>

          {/* Date and Time Information */}
          <Card className="p-3">
            <div className="space-y-2">
              <h3 className="flex items-center gap-2">
                <Calendar className="h-4 w-4" />
                Datum & Zeit
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                <div>
                  <label className="text-sm text-muted-foreground">Datum</label>
                  <p className="font-medium">{entry.date}</p>
                </div>
                <div>
                  <label className="text-sm text-muted-foreground">Dauer</label>
                  <p className="font-medium">{entry.duration}</p>
                </div>
                {entry.isMultiDay && entry.endDate && (
                  <div className="md:col-span-2">
                    <label className="text-sm text-muted-foreground">Fehlzeit bis</label>
                    <p className="font-medium flex items-center gap-2">
                      <Calendar className="h-4 w-4" />
                      {entry.endDate}
                    </p>
                  </div>
                )}
                {entry.dateRange && (
                  <div className="md:col-span-2">
                    <label className="text-sm text-muted-foreground">Zeitfenster</label>
                    <p className="font-medium flex items-center gap-2">
                      <Clock className="h-4 w-4" />
                      {entry.dateRange}
                    </p>
                  </div>
                )}
              </div>
            </div>
          </Card>

          {/* Status */}
          <Card className="p-3">
            <div className="space-y-2">
              <h3 className="flex items-center gap-2">
                <Shield className="h-4 w-4" />
                Status
              </h3>
              <StatusDisplay status={entry.status} endDate={entry.endDate} isMultiDay={entry.isMultiDay} />
            </div>
          </Card>

          {/* Reason */}
          <Card className="p-3">
            <div className="space-y-2">
              <h3 className="flex items-center gap-2">
                <FileText className="h-4 w-4" />
                Grund
              </h3>
              <p className="text-sm leading-relaxed">{entry.reason || 'Kein Grund angegeben'}</p>
            </div>
          </Card>

          {/* Attachment */}
          <Card className="p-3">
            <div className="space-y-2">
              <h3 className="flex items-center gap-2">
                <Paperclip className="h-4 w-4" />
                Nachweis
              </h3>
              <AttachmentDisplay hasAttachment={entry.hasAttachment} hasAccess={entry.hasAccess} />
            </div>
          </Card>

          <Separator />

          {/* Meta Information */}
          <div className="space-y-1 text-sm text-muted-foreground">
            <div className="flex justify-between">
              <span>Erstellt von:</span>
              <span>{entry.createdBy}</span>
            </div>
            <div className="flex justify-between">
              <span>Erstellt am:</span>
              <span>{entry.createdAt}</span>
            </div>
            {entry.lastEditedBy && entry.lastEditedAt && (
              <>
                <div className="flex justify-between">
                  <span>Zuletzt bearbeitet von:</span>
                  <span>{entry.lastEditedBy}</span>
                </div>
                <div className="flex justify-between">
                  <span>Zuletzt bearbeitet am:</span>
                  <span>{entry.lastEditedAt}</span>
                </div>
              </>
            )}
          </div>

          {/* Action Buttons */}
          <div className="flex justify-between pt-3">
            <Button variant="outline" onClick={onClose}>
              Schließen
            </Button>
            <div className="flex gap-2">
              <Button
                variant="outline"
                onClick={() => {
                  onEdit(entry);
                  onClose();
                }}
              >
                <Edit2 className="h-4 w-4 mr-2" />
                Bearbeiten
              </Button>
              <Button
                variant="destructive"
                onClick={handleDelete}
              >
                <Trash2 className="h-4 w-4 mr-2" />
                Löschen
              </Button>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}

// src/Components/FehlzeitDetailModal.vue
<template>
  <div v-if="isOpen && entry" class="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4">
    <div 
      class="bg-background border border-border rounded-lg w-full max-w-2xl max-h-[90vh] overflow-y-auto"
      @click.stop
    >
      <!-- Header -->
      <div class="p-4 border-b border-border">
        <h2 class="flex items-center gap-2">
          <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
          </svg>
          Fehlzeit Details
        </h2>
      </div>

      <!-- Content -->
      <div class="p-4 space-y-4">
        <!-- Student Information -->
        <div class="p-3 bg-card border border-border rounded-lg">
          <div class="space-y-2">
            <h3 class="flex items-center gap-2">
              <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
              </svg>
              Schüler*in
            </h3>
            <div>
              <div class="flex items-center gap-2">
                <span class="font-medium">{{ entry.studentName }}</span>
                <span class="px-2 py-1 text-xs bg-secondary text-secondary-foreground rounded border">
                  {{ entry.studentClass }}
                </span>
              </div>
            </div>
          </div>
        </div>

        <!-- Source Type -->
        <div class="p-3 bg-card border border-border rounded-lg">
          <div class="space-y-2">
            <h3 class="flex items-center gap-2">
              <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              Art der Meldung
            </h3>
            <div class="flex items-center gap-2">
              <span 
                v-if="entry.sourceType === 'eltern-app'"
                class="inline-flex items-center gap-1 px-3 py-1 text-xs bg-blue-50 text-blue-700 border border-blue-200 rounded"
              >
                <svg class="h-3 w-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                Eltern-App
              </span>
              <span 
                v-if="entry.sourceType === 'anwesenheit'"
                class="inline-flex items-center gap-1 px-3 py-1 text-xs bg-orange-50 text-orange-700 border border-orange-200 rounded"
              >
                <svg class="h-3 w-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                </svg>
                Anwesenheit/Klassenbuch
              </span>
              <span 
                v-if="entry.sourceType === 'schuleingabe'"
                class="inline-flex items-center gap-1 px-3 py-1 text-xs bg-purple-50 text-purple-700 border border-purple-200 rounded"
              >
                <svg class="h-3 w-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                </svg>
                Schuleingabe
              </span>
            </div>
          </div>
        </div>

        <!-- Date and Time Information -->
        <div class="p-3 bg-card border border-border rounded-lg">
          <div class="space-y-2">
            <h3 class="flex items-center gap-2">
              <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
              </svg>
              Datum & Zeit
            </h3>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-3">
              <div>
                <label class="text-sm text-muted-foreground">Datum</label>
                <p class="font-medium">{{ entry.date }}</p>
              </div>
              <div>
                <label class="text-sm text-muted-foreground">Dauer</label>
                <p class="font-medium">{{ entry.duration }}</p>
              </div>
              <div v-if="entry.dateRange" class="md:col-span-2">
                <label class="text-sm text-muted-foreground">Zeitfenster</label>
                <p class="font-medium flex items-center gap-2">
                  <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  {{ entry.dateRange }}
                </p>
              </div>
            </div>
          </div>
        </div>

        <!-- Status -->
        <div class="p-3 bg-card border border-border rounded-lg">
          <div class="space-y-2">
            <h3 class="flex items-center gap-2">
              <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
              </svg>
              Status
            </h3>
            <StatusPill :status="entry.status" />
          </div>
        </div>

        <!-- Reason -->
        <div class="p-3 bg-card border border-border rounded-lg">
          <div class="space-y-2">
            <h3 class="flex items-center gap-2">
              <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Grund
            </h3>
            <p class="text-sm leading-relaxed">{{ entry.reason || 'Kein Grund angegeben' }}</p>
          </div>
        </div>

        <!-- Attachment -->
        <div class="p-3 bg-card border border-border rounded-lg">
          <div class="space-y-2">
            <h3 class="flex items-center gap-2">
              <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13" />
              </svg>
              Nachweis
            </h3>
            <div v-if="!entry.hasAttachment" class="flex items-center gap-2 text-muted-foreground">
              <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              <span>Kein Nachweis vorhanden</span>
            </div>
            <div v-else-if="!entry.hasAccess" class="flex items-center gap-2 text-muted-foreground">
              <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
              </svg>
              <span>Nachweis vorhanden (kein Zugriff)</span>
            </div>
            <div v-else class="flex items-center gap-2 text-foreground">
              <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13" />
              </svg>
              <span>Nachweis vorhanden</span>
              <button class="px-3 py-1 text-sm border border-input bg-background hover:bg-accent rounded">
                Anzeigen
              </button>
            </div>
          </div>
        </div>

        <!-- Separator -->
        <div class="border-t border-border"></div>

        <!-- Meta Information -->
        <div class="space-y-1 text-sm text-muted-foreground">
          <div class="flex justify-between">
            <span>Erstellt von:</span>
            <span>{{ entry.createdBy }}</span>
          </div>
          <div class="flex justify-between">
            <span>Erstellt am:</span>
            <span>{{ entry.createdAt }}</span>
          </div>
          <div v-if="entry.lastEditedBy && entry.lastEditedAt" class="flex justify-between">
            <span>Zuletzt bearbeitet von:</span>
            <span>{{ entry.lastEditedBy }}</span>
          </div>
          <div v-if="entry.lastEditedBy && entry.lastEditedAt" class="flex justify-between">
            <span>Zuletzt bearbeitet am:</span>
            <span>{{ entry.lastEditedAt }}</span>
          </div>
        </div>

        <!-- Action Buttons -->
        <div class="flex justify-between pt-3">
          <button
            type="button"
            class="px-4 py-2 border border-input bg-background hover:bg-accent rounded-md"
            @click="$emit('close')"
          >
            Schließen
          </button>
          <div class="flex gap-2">
            <button
              type="button"
              class="flex items-center gap-2 px-4 py-2 border border-input bg-background hover:bg-accent rounded-md"
              @click="handleEdit"
            >
              <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
              </svg>
              Bearbeiten
            </button>
            <button
              type="button"
              class="flex items-center gap-2 px-4 py-2 bg-destructive text-destructive-foreground hover:bg-destructive/90 rounded-md"
              @click="handleDelete"
            >
              <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
              </svg>
              Löschen
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import StatusPill from './StatusPill.vue'

const props = defineProps({
  entry: Object,
  isOpen: Boolean
})

const emit = defineEmits(['close', 'edit', 'delete'])

const handleEdit = () => {
  emit('edit', props.entry)
  emit('close')
}

const handleDelete = () => {
  if (confirm('Fehlzeit wirklich löschen?')) {
    emit('delete', props.entry.id)
    emit('close')
  }
}
</script>
